theme: jekyll-theme-minimal

title: "Columbia MA Math Camp 2023"
description: "Information and Course Material for the 2023 Math Camp of the MA in Economics at Columbia University"
logo: "Columbia_University_shield.png"
show_downloads: true

markdown: kramdown